# Generated by Django 5.1.4 on 2024-12-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0002_attemptcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
