# Generated by Django 5.1.4 on 2024-12-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0003_click_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'verbose_name': 'Hvor mange har klikket', 'verbose_name_plural': 'Klik'},
        ),
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'verbose_name': 'Hvor mange har skrevet sin kode', 'verbose_name_plural': 'Forsøgstællere'},
        ),
    ]
